apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  labels:
    name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: amazon.dev
    http:
      paths:
      - pathType: Prefix
        path: /api/users/?(.*)
        backend:
          service:
            name: auth-srv
            port:
              number: 3000
      - pathType: Prefix
        path: /api/products/?(.*)
        backend:
          service:
            name: products-srv
            port:
              number: 8080
      - pathType: Prefix
        path: /api/cart/?(.*)
        backend:
          service:
            name: cart-srv
            port:
              number: 8080
      - pathType: Prefix
        path: /api/orders/?(.*)
        backend:
          service:
            name: orders-srv
            port:
              number: 3000
      - pathType: Prefix
        path: /api/payments/?(.*)
        backend:
          service:
            name: payments-srv
            port:
              number: 3000
      - pathType: Prefix
        path: /?(.*)
        backend:
          service:
            name: client-srv
            port:
              number: 3000
